# Check out https://docs.codemagic.io/getting-started/yaml/ for more information

workflows:
    flutter-package:
        name: dargon2 Tests
        environment:
            dart: beta
        scripts:
            - pub get
            - dart test
