name: dargon2
description: Provides bindings for hashing and verifying with Argon2, the winner of the Password Hashing Competition.
version: 2.0.1
homepage: https://github.com/tmthecoder/dargon2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dargon2_core: '^1.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4

