name: dargon2
description: Provides bindings for hashing and verifying with Argon2, the winner of the Password Hashing Competition.
version: 1.1.0
homepage: https://github.com/tmthecoder/dargon2

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  ffi: ^0.1.3
  convert: ^2.1.1
  meta: ^1.2.3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4

