name: dargon2_flutter

on:
  push:
  pull_request:

defaults:
  run:
    working-directory: dargon2_flutter/dargon2_flutter/example

jobs:
  test_android:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}
      - name: AVD cache
        uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-30
      - name: Download Flutter
        uses: subosito/flutter-action@v1.5.1
        with:
          channel: 'stable'
          cache: true
      - name: Upgrade flutter
        run: flutter upgrade
      - name: Run Integration Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          avd-name: android_tester
          force-avd-creation: false
          script: flutter test -d android_tester integration_test/
#
#  test_ios:
#    runs-on: macos-latest
#    steps:
#      - name: checkout
#        uses: actions/checkout@v2
#      - name: List Simulators
#        run: xcrun instruments -s
