name: dargon2

on:
  push:
  pull_request:

defaults:
  run:
    working-directory: dargon2

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
    - uses: actions/checkout@v2
    - uses: dart-lang/setup-dart@v1
    - name: Install dependencies
      run: dart pub get
    - name: Run tests
      run: dart pub run test
