name: dargon2

on:
  push:
  pull_request:

defaults:
  run:
    working-directory: dargon2

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
