name: dargon2

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
    - uses: actions/checkout@v2
    - name: move to dargon2 main lib
      run: cd dargon2 && ls
    - name: Install dependencies
      run: ls && pub get
    - name: Run tests
      run: pub run test
