name: Library Builder CI

on:
  repository_dispatch:
  workflow_dispatch: 

defaults:
  run:
    working-directory: dargon2

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make library
      run: |
        git clone https://github.com/P-H-C/phc-winner-argon2.git argon2_library
        cd argon2_library
        make
    - name: push compiled library
      run: |
        mkdir -p lib/src/blobs/
        cp argon2_library/libargon2.so.1 lib/src/blobs/libargon2-linux.so
        git add -f lib/src/blobs/libargon2-linux.so
        git config user.name  "Github Actions"
        git config user.email "GH-actions-ci@github.com"
        git remote add secure-origin https://${{ secrets.ACCESS_TOKEN }}@github.com/tmthecoder/argon2_dart.git
        git fetch --unshallow secure-origin main
        git commit -m "create blobs for linux"
        git push -f secure-origin main

  mac-build:
    runs-on: macos-latest
    needs: linux-build
    steps:
    - uses: actions/checkout@v2
    - name: make library
      run: |
        git clone https://github.com/P-H-C/phc-winner-argon2.git argon2_library
        cd argon2_library
        make
    - name: copy and push library
      run: |
        cp argon2_library/libargon2.1.dylib lib/src/blobs/libargon2-darwin.dylib
        git add -f lib/src/blobs/libargon2-darwin.dylib
        git config user.name  "Github Actions"
        git config user.email "GH-actions-ci@github.com"
        git remote add secure-origin https://${{ secrets.ACCESS_TOKEN }}@github.com/tmthecoder/argon2_dart.git
        git commit -m "create blobs for mac"
        git fetch --unshallow secure-origin main
        git pull secure-origin main
        git push secure-origin main
        
  windows-build:
    runs-on: windows-latest
    needs: [linux-build, mac-build]
    steps:
      - uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Install Windows 8.1 SDK
        shell: powershell
        run: |
          Invoke-WebRequest -Method Get -Uri https://go.microsoft.com/fwlink/p/?LinkId=323507 -OutFile sdksetup.exe -UseBasicParsing
          Start-Process -Wait sdksetup.exe -ArgumentList "/q", "/norestart", "/features", "OptionId.WindowsDesktopSoftwareDevelopmentKit", "OptionId.NetFxSoftwareDevelopmentKit"
      - name: make library
        run: |
          git clone https://github.com/P-H-C/phc-winner-argon2.git argon2_library
          CD argon2_library
          msbuild Argon2.sln /p:Configuration=ReleaseStatic
      - name: copy and push library
        run: |
          Copy-Item “argon2_library\vs2015\build\Argon2OptDll.dll” -Destination “lib\src\blobs\libargon2-win.dll”
          git add -f lib\src\blobs\libargon2-win.dll
          git config user.name  "Github Actions"
          git config user.email "GH-actions-ci@github.com"
          git remote add secure-origin https://${{ secrets.ACCESS_TOKEN }}@github.com/tmthecoder/argon2_dart.git
          git commit -m "create blobs for mac"
          git fetch --unshallow secure-origin main
          git pull secure-origin main
          git push secure-origin main
      
